### ISSUE TITLE
Doesn't Seem to Work

### ISSUE THREAD

**Issue by aprather51** [SebastianMC/obsidian-custom-sort#103]
It doesn't seem to work on my end (Obsidian v1.4.16 on Windows 11 latest build)

Reading View
![image](https://github.com/SebastianMC/obsidian-custom-sort/assets/10257247/bc8bc7ed-2d3f-404e-bc44-1bc439c28fc5)

Source View
![image](https://github.com/SebastianMC/obsidian-custom-sort/assets/10257247/c9a29acc-8ec9-46dc-90c6-c4632f41723f)

Plugin Setup
![image](https://github.com/SebastianMC/obsidian-custom-sort/assets/10257247/6c902b80-8dc7-4a5d-853c-9feaab819dcd)

What am I missing here?

**Comment by aprather51** [comment]
Disregard this; The issue was on my end. Apparently, I realize I'd need to turn on sorting button from the ribbon bar to be able see the action.

Perhaps, the documentaion could have been better if it doesn't clutter between mobile and desktop. Great plugin, thank you.

**Comment by SebastianMC** [comment]
A very short-lived issue :-)
Your remark about the ribbon button is very valid and I encounter it in user's feedback.
Would it help if you knew a command palette **sort on** worked in an equivalent way?
