### ISSUE TITLE
broken link in README

### ISSUE THREAD

**Issue by notuntoward** [SebastianMC/obsidian-custom-sort#104]
In the README, the link

> [long and much more detailed advanced-README.md is here](https://github.com/SebastianMC/advanced-README.md)

is 404

**Comment by SebastianMC** [comment]
Hi @notuntoward 

thank you very much for catching this and reporting!

I was not aware that github changed the way how relative links to docs and images work in README.md (and related).

Links should be correct now.

thanks!

**Comment by notuntoward** [comment]
Thanks for the update.
