### ISSUE TITLE
Sorting doesn't work

### ISSUE THREAD

**Issue by piotrnajda3000** [SebastianMC/obsidian-custom-sort#113]
Hi, I'm trying to get it to work, but wasn't able to. Works on a clean vault. Any ideas on what might be the issue? Thank you. (Sorting by file name A -> Z). 

https://github.com/SebastianMC/obsidian-custom-sort/assets/58721991/8bf376eb-5d17-40b5-8029-a06d88d09623

**Comment by SebastianMC** [comment]
Hi @piotrnajda3000,

thanks for the report and very informative video, including the console view and the entire vault UI!\
It really helps to move forward any investigation!

At a glance I can see two File Explorer icons in the top toolbar, very unusual - if both represent File Explorer. Technically, the custom sort plugin assumes there is only a single instance of File Explorer. So a potential investigation path.\
To confirm, could you please repeat the scenario presented on the video with one additional step at the end? Namely, please create a new note or folder anywhere in the same File Explorer, at root level. Creating a new item in File Explorer automatically triggers (re)sorting.

What hides behind the File Explorer icon on the left side of the active one? Is this another instance of File Explorer indeed?

BTW I assume that you don't have any textual sorting specification in file, that is the `sorting-spec: |....` entry in metadata somewhere. Such a configuration could potentially override the order set in bookmarks.

Also, I can see some additional ribbon icons coming from various plugins - maybe there is some conflict between plugins.

Anyways, please do the simple test described above and let me know.

Potential further troubleshooting steps could include running the custom-sort plugin with debugging output enabled

**Comment by piotrnajda3000** [comment]
> At a glance I can see two File Explorer icons in the top toolbar, very unusual 

This was it! The second Folder icon seems to have appeared through the MAKE.MD community plugin -- the icon persist even after having disabled it. Sorting works with the "first" file explorer. 

Thank you.
