### ISSUE TITLE
Plugin ignores sort spec sort order

### ISSUE THREAD

**Issue by lazlo2424** [SebastianMC/obsidian-custom-sort#121]
The plugin sorts the files and folders equally (Wonderful), however no configuration sorts a to z, instead it is always z - a
Here is the configuration file I am using

I have also switched to > a-z but the sort is always backwards.
The documentation says it should just work but maybe I am missing something.

sorting-spec: |
 //
 // A simple configuration for obsidian-custom-sort plugin
 // (https://github.com/SebastianMC/obsidian-custom-sort)
 // It causes the plugin to take over the control of the order of items in the root folder ('/') of the vault
 // It explicitly sets the sorting to ascending ('<') alphabetical ('a-z')
 // Folders and files are treated equally by the plugin (by default) so expect them intermixed
 // after enabling the custom sort plugin
 // 
 target-folder: /*
 < a-z
---

**Comment by SebastianMC** [comment]
Hi @lazlo2424,

the problem which you encountered seems to be very confusing and I think that the quickest way of verification is to re-start from scratch.
Please ensure that you have only a single note `sortspec` (the underlying file is `sortspec.md`).
If you have multiple instances of `sortspec` notes, delete all of them and create a single empty one from scratch in the root folder of the vault.
Open the `sortspec` note (in Obsidian) and enable the `source mode` (menu `View -> Source Mode`). This will prevent the Obsidian properties editor from interfering.
Having done the above, type in the simplest sorting specification as below, exactly as visible with the exact indentation (two spaces) on the two lines `  target-folder: /*` and `  < a-z`:

```yaml
---
sorting-spec: |
  target-folder: /*
  < a-z
---
```

After that click the ribbon button (once or twice) to reload the sorting specification and apply it.
The alphabetical (a to z) sorting should be applied in result.
Finally, remember to disable the `source mode` (menu `View -> Source Mode`)

If you have further questions or concerns, please continue here

**Comment by lazlo2424** [comment]
Thanks for the reply.

You are correct.  It is very strange.

I think I will make a video of me doing it as I have been very careful to closely follow the very detailed instructions…

The sorting of files and folders worked perfectly as they merged together.
It was only the sort order that did not work.

Video coming shortly..

**Comment by lazlo2424** [comment]
It is worth noting that once the sortspec configuration is stored in the front matter of the sortspec.md file, it will become invisible if you are hiding properties within Obsidian.
This reported issue was user error on my part and I am going to close the issue accordingly.

**Comment by SebastianMC** [comment]
Hi @lazlo2424 

thank you for your input!

Your voice was important and was a direct reason to create #125, which could improve user experience and prevent issued like you encountered.

thanks!
