### ISSUE TITLE
A race condition (first observed for Obsidian 1.6.3) could cause the plugin not to apply the custom sort automatically on vault opening / loading or app (re)loading

### ISSUE THREAD

**Issue by SebastianMC** [SebastianMC/obsidian-custom-sort#147]
First observed in Obsidian 1.6.3
(Re)opening a vault shows the custom sorting is active (ribbon icon) and the notifications also tell that the custom sorting was applied. At the same time File Explorer items are sorted with standard Obsidian. You need to explicitly apply the custom sorting (ribbon icon click or command from commands palette) to make it work.

Yet another Obsidian breaking change made in not-backward compatible way?

Affected scenarios:
- starting the Obsidian app and opening a vault
- restarting the Obsidian app and (automatic) opening a vault
- forced reload of the vault (from Obsidian UI menu)

Pending investigation (classified as `retro bug` resulting from Obsidian update)

**Comment by SebastianMC** [comment]
First observation - disabling or uninstalling the DataView plugin resolves the problem. A dependency???

**Comment by SebastianMC** [comment]
Observation: it looks like a race condition between some of system (Obsidian) plugin-specific events.

**Comment by SebastianMC** [comment]
Plugin release [2.1.11](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/2.1.11) was released with the fix.

**Comment by Azmoinal** [comment]
I'm not sure if it is a side effect of this fix but on my ipad/iphone at restart of Obsidian there a several notifications reporting that "custom order applied correctly".

I've the option for custom order status change notification enabled on mobile.

Tomorrow, I could check if the same happen on the desktop.

Anyway the custom order is applied correctly, it is only a matter to receive sometimes two or four/five times the initial notification.

**Comment by SebastianMC** [comment]
Hi @Azmoinal 

thank you very much for your report!
Indeed when retested on ipad I'm observing the same behavior (screenshot below).
In general, it is better to have superfluous notifications and correct sorting applied automatically than no custom sorting applied. At the same time, the multiple notifications deserve investigation. I will open a separate ticket for that behavior.

![IMG_B31A38660AE0-1](https://github.com/SebastianMC/obsidian-custom-sort/assets/23032356/9d8ae707-24d0-46e2-b78d-8b8eff466aea)
