### ISSUE TITLE
[mobile] Multiple notifications generated upon Obsidian startup

### ISSUE THREAD

**Issue by SebastianMC** [SebastianMC/obsidian-custom-sort#149]
As a result of internal changes in Obsidian 1.6.x for plugin lifecycle and probably related to the bugfix #147 a series of notifications is shown by the plugin on start on mobile (screenshot below). 

While it is better to have superfluous notifications and correct sorting applied automatically than no custom sorting applied, the multiple notifications deserve investigation and fixing.

First reported by @Azmoinal in [this comment](https://github.com/SebastianMC/obsidian-custom-sort/issues/147#issuecomment-2163734590) under #147

---
Screenshot for context
![IMG_B31A38660AE0-1](https://github.com/SebastianMC/obsidian-custom-sort/assets/23032356/9d8ae707-24d0-46e2-b78d-8b8eff466aea)

**Comment by SebastianMC** [comment]
Some further observations: the multi-notification on mobile seem to happen rarely, not in day-to-day use. Opening, switching, reopening a vault, closing, exiting, etc. don't cause the superfluous notifications flow.

The screenshot attached to this ticket comes from scenario when the Obsidian app and the vault hasn't been open for a while (a month or so).

At code level the notifications are generated only when the plugin is initialized by Obsidian. Multiple repeated notifications suggest some kind of auto-restarting of plugins subsystem by Obsidian. Hence a correct response of the plugin to Obsidian-generated events.

Need to collect more observations - as for now this seem to be a minor issue occurring in some edge cases.

**Comment by Azmoinal** [comment]
I agree with you, it is not a breaking point. I'm not sure but opening my vault it seems frequent, only at opening. 

After that I can work without any other notification. I'll try to find a way to reproduce it. I'll keep you informed.

Anyway @SebastianMC thanks a lot for you effort in maintaining the plugin.

**Comment by SebastianMC** [comment]
Did some more investigation and the final conclusion is to keep the behavior as-is.
Background:
- showing superfluous notifications upon vault (re)open doesn't impact the sorting functionality
- showing the notifications is driven by Obsidian system events: plugin load, first refresh of the metadata cache, there is also a scenario driven by loading of File Explorer by Obsidian, if it is delayed. And eventually there is the most obvious scenario, when the sorting is applied, implicitly or explicitly. Some sequences of these events could indeed cause multiple notifications. At the same time it is not feasible to try to finetune the logic to recognize each of edge scenarios to determine if to show or not the notification
- potential solution would be to prevent subsequent notifications time-based, e.g. 500 ms of time buffer. At the same time seems to be an overkill - superfluous notifications on vault (re)opening don't hurt

Based on the above, closing the ticket.
