### ISSUE TITLE
Sort notes in dd-Mmm-yyyy format

### ISSUE THREAD

**Issue by DvValk** [SebastianMC/obsidian-custom-sort#151]
Personally I think the date format: dd-Mmm-yyyy is superior to all others as there is no confusion possible between different parts of the world. However, it is horrible while trying to sort. Would it be hard for you to implement this into your nice plugin? Or maybe it is already possible, but I just don't know how to create the correct yaml file? 

e.g.: 
20-Nov-2024
05-May-2024
26-Dec-2023
13-Oct-2020

Thanks!

**Comment by SebastianMC** [comment]
Hi @DvValk 

thanks for reporting this feature request!
This sorting method is not supported yet. It doesn't fall into category of numerical or alphabetical, and cannot be easily translated to / mapped to alphabetical or numericalbecause of month names - requires some arbitrary ordering.

At the same time implementing this is trivial, thus adding it to the list of enhancements (the first one to be done).

**Comment by DvValk** [comment]
Awesome, thanks for putting it on your to-do list! Looking forward to it :)

**Comment by SebastianMC** [comment]
Implementation completed, a robust example from tests:

<img width="500" alt="2024-07-10_12-05-09" src="https://github.com/SebastianMC/obsidian-custom-sort/assets/23032356/acc5b1f0-0151-4f8e-a627-44c73e06f934">

The exact sorting spec above:
```yaml
---
sorting-spec: |
  /+ \[dd-Mmm-yyyy]
  /+ ... \[dd-Mmm-yyyy]
  /+ \[dd-Mmm-yyyy] ...
    < a-z
---
```

The newly introduced syntax `\[dd-Mmm-yyyy]` can be used to match note titles (or part of titles) containing dates in that specific format, all case sensitive (the syntax and the months in note titles).
The above example takes advantage of the `/+` to combine multiple criteria. It can be read as:

- `/+ \[dd-Mmm-yyyy]` - if a note title comprises only date in that format, OR
- `/+ ... \[dd-Mmm-yyyy]` if a note title ends with date in that format, OR
- `/+ \[dd-Mmm-yyyy] ...` if a note title starts with date in that format, THEN
- `  < a-z` group the notes and sort by that date, the oldest date first

A simpler example for a folder `Attachments` containing the notes / files or subfolders with names comprising only the date, to be sorted with the newest pushed to the top, would look like:
```yaml
---
sorting-spec: |
  target-folder: Attachments
  \[dd-Mmm-yyyy]
    > a-z
---
```

This feature available in the ... TBD release of the plugin

**Comment by DvValk** [comment]
Many thanks @SebastianMC, it works like a charm and makes my project folders very clear!

**Comment by andre-000** [comment]
@SebastianMC anyway to use a similar sorting method but for the Mmm-dd-yyyy format (e.g. Jan-01-2025)?

**Comment by SebastianMC** [comment]
Hi @andre-000 

> anyway to use a similar sorting method but for the Mmm-dd-yyyy format (e.g. Jan-01-2025)?

this was a low-hanging-fruit, a new [2.1.5](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/2.1.15) has been exposed with this feature.

The relevant pattern to use is ` \[Mmm-dd-yyyy]`

An example sorting spec to capture files and folders with a date suffix in that format:

```yaml
---
sorting-spec: |
  target-folder: Attachments
  ... \[Mmm-dd-yyyy]
    > a-z
---
```
