### ISSUE TITLE
Plugin closes most recent tab

### ISSUE THREAD

**Issue by jamie9090** [SebastianMC/obsidian-custom-sort#17]
With the plugin enabled, upon opening Obsidian, the most recent tab gets closed automatically.
With the plugin disabled, I have no issues.

I am able to repeat this behaviour by opening or closing Obsidian.,
I am also able to repeat this behaviour by disabling and re-enabling the plugin without closing Obsidian.

I am not unable to repeat this by just suspending or re-enabling the custom sort function. It seem like it's really on that "first load".

**Comment by SebastianMC** [comment]
Thank you, a good catch!
Fix releases a minute ago

**Comment by jamie9090** [comment]
Legend - thank you!
