### ISSUE TITLE
Feature Request: Disable Status bar entry

### ISSUE THREAD

**Issue by MSzturc** [SebastianMC/obsidian-custom-sort#3]
Please make the 'Custom sort: ON/OFF' Status-Element configurable. In my setup i would like to hide it since my statusbar ist pretty full and i would like to get rid of informations that i don't need for my workflow

**Comment by MSzturc** [comment]
That was fast, thx for your effort :-)

**Comment by SebastianMC** [comment]
You're welcome @MSzturc !
Keeping my hands in large projects at work it is a nice relax to touch something small in a free evening, if time permits ;-)
