### ISSUE TITLE
Cannot download sourcespec.md

### ISSUE THREAD

**Issue by SSSidekick** [SebastianMC/obsidian-custom-sort#30]
The documentation for this plugin states that one should download the sourcespec.md and place it in the folder to be sorted. But when clicking on the link, nothing happens. I am not sure what needs to be in the frontmatter of that note and so I am unable to use this plugin.

**Comment by SebastianMC** [comment]
Hi @SSSidekick 

for a direct help: please use the 'Download linked file' (or 'Save link as...') browser function on the link below:

[sortspec.md](https://raw.githubusercontent.com/SebastianMC/obsidian-custom-sort/master/docs/examples/quickstart/sortspec.md)

Make sure that you name the downloaded file exactly as `sortspec.md` (not `sortspec`, not `sortspec.md.html`, not `sortspec.html`, etc.)

Long term: could you please point me exactly which link in readme is not functioning for you?

I'm aware of the tricky Github web UI behavior for files exposed for direct downloads (also for security reasons) and I'm thinking about some additional small download instructions.

**Comment by SebastianMC** [comment]
Hi @SSSidekick 

one more thing: would you find two minutes to take a look at the [updated TL;DR](https://github.com/SebastianMC/obsidian-custom-sort#tldr-usage) section of README.md to see, if the download instructions for `sortspec.md` are cleaner now, from your perspective?

I've added some additional details and clarifications, hopefully helpfull

thanks in advance,
Seb

**Comment by SebastianMC** [comment]
Not having further feedback from @SSSidekick this or either way, I'm closing this ticket.
Hopefully the updated README.md (specifically for downloads) addressed the original issues
