### ISSUE TITLE
[Feature Request] Include default "collapsed" state for folders?

### ISSUE THREAD

**Issue by wwwald** [SebastianMC/obsidian-custom-sort#33]
Awesome plugin, has cleared up my whole daily journal tree!

I've been wanting a similar thing for the "collapsed" state of folders.
For example, I have a "contacts" folders that contains about 900 individual files by now. Whenever I add a contact, this folders gets expanded in the file explorer, causing a whole lot of scrolling to make it collapsed again. If the YAML sorting language would include a default "collapsed" state too, this could be automated. I wouldn't need to manually collapse folders like "contacts" 12 times a day.

So: would it be hard to add a default "collapsed" state to the YAML spec?

**Comment by SebastianMC** [comment]
Hi @wwwald

my first impressions are:
- 'collapse' folder function seems unrelated and out of scope of the folder items ordering plugin
- technically the point of integration of Obsidian to perform folder collapse is probably different than the one for items sorting
- at a glance, the Obsidian events to be handled also seem different

Yet, before saying a definite _no_ to the idea of 'collapse feature' I think I can give it a second chance. There is always a place for a hidden or advanced feature, if it is useful and doesn't interfere with the main function of the module.

To take a closer look I need to better understand the requested function and/or relevant scenarios:
- I understand that the starting point would be setting some 'collapsed' flag in YAML for a folder
- in result the folder should remain collapsed, correct? 
- 'keep collapsed' from technical perspective means imposing the collapse action in reaction to an event which would expand the folder. Or going the hard way and simply removing all folder items from the view - yet this action could not be simply undone.

The more I think about it, the less clear it becomes how the feature should work from the user perspective. And what is the actual expected outcome? Is it the collapse operation indeed or maybe hiding the items?

Maybe all you need is a function 'hide all items in a folder'? Not really a collapse operation, but maybe sufficient? In that case, to see the list of items in a folder again you would need to turn off the custom sorting (via ribbon button). Implementation of such 'hide all items' looks trivial, on top on current version of the plugin

What do you think?
Could you  please share some more insight on that?

thanks,
Seb

**Comment by SebastianMC** [comment]
Hi @wwwald 

not having further input from you since Nov '22, I'm closing the ticket.
Feel free to reopen it if we can discuss it further

thanks,
Seb
