### ISSUE TITLE
Ensure the exact file name is sortspec.md (or just sortspec if Obsidian automatically appends .md)

### ISSUE THREAD

**Issue by skvale** [SebastianMC/obsidian-custom-sort#37]
It took me a while to realize my sortspec.md file was really named sortspec.md.md and I had to rename it to just sortspec

Perhaps it would help others to mention that in the README

**Comment by SebastianMC** [comment]
Hi @skvale 

this is an excellent catch indeed!

Update of documentation is one thing, and at the same time a simple enhancement of the plugin to scan both 'sortspec.md' and 'sortspec.md.md' files. Such a fix was already applied to the note name which can be entered in plugin settings. Let computers take care of such details, not humans ;-)

thanks!
Seb

**Comment by SebastianMC** [comment]
Thanks for your contribution in the PR!
I've asked for a small change there, please take a look and prepare for merge
