### ISSUE TITLE
Allow for different folder note naming scheme

### ISSUE THREAD

**Issue by FynnFreyer** [SebastianMC/obsidian-custom-sort#53]
While giving the folder note the same name as the folder is certainly customary, another popular approach is specifying an index name (e.g. `README.md` or `__about__.md`) for folder notes.

Both [xpgo's](https://github.com/xpgo/obsidian-folder-note-plugin) and [aidenlx's](https://github.com/aidenlx/alx-folder-note) very popular folder note plugins support this approach.

It would be nice, if Obsidian Custom Sort would also support this.

**Comment by FynnFreyer** [comment]
Very useful plugin btw, thanks for making this!
Also, since you can simply use a sortspec file in the folder, this is really just a nice to have ...

**Comment by SebastianMC** [comment]
Hi @FynnFreyer 

thanks for the suggestion!

Actually it was a _very_ low hanging fruit, becase... it was already supported, yet the setting description was not fully clear.

I've updated the description in settings panel to be precise. And also - to make the feature more user friendly - extended the code accept both `_about_` and `_about_.md` inputs in the configuration. Based on the feedback which I receive people tend to confuse note name with file name, so accepting both variants eliminates the confusion.

Release [1.6.1](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/1.6.1) is ready

![updated-settings](https://user-images.githubusercontent.com/23032356/218096391-457dccea-7cea-45bd-a896-91777f37d7de.png)

**Comment by FynnFreyer** [comment]
Very nice! Thanks for adding some clarification on thin =)

**Comment by FynnFreyer** [comment]
*this

**Comment by joellti** [comment]
@SebastianMC Can you please support `Outside Folder, with Same Name` mode from https://github.com/aidenlx/alx-folder-note/wiki/folder-note-pref as well. All my notes are currently in this mode and I don't want to convert to other modes since it brings other benefits. Thx a lot.
