### ISSUE TITLE
[Feature Request] Hiding files/Folders

### ISSUE THREAD

**Issue by replete** [SebastianMC/obsidian-custom-sort#61]
I'm not sure if this fits this plugin or not. 

I have a pesky `Context` folder that is being generated by something, maybe `DB Folder` and I thought this plugin would probably have a hide feature. It doesn't appear to, so here's a suggestion!

This plugin has such a great approach to tweaking the file explorer view, which is at this point our main vault navigation so perhaps it might be a nice feature addition.

Off the top of my head, an entry in sortspec like `!Foldername` would just hide it.

Thanks again for a great plugin. 

Phil

**Comment by SebastianMC** [comment]
Hiding files or folders is supported by the plugin from the very beginning as an advanced and experimental feature, not documented.

At this point I think that documenting it in a section like _experimental features_ wouldn't hurt, I will do it.

There are some unobvious (and potentially confusing) ramifications of hiding a folder or file using this plugin:
- the file or folder, while not being visible in File Explorer, still exists in the Vault and can be accessed (e.g. open for editing) by other means like search or a link in other note, etc.
- the Obsidian UI context menu function _Reveal file in navigation_  becomes void and has no effect, which could be confusing. At least it doesn't crash or block Obsidian.
- if a file is hidden via this plugin, its parent folder goes under control of the plugin, which means the standard UI-selected sorting order doesn't apply to the folder. So, hiding a file requires you to also manage the sorting of its parent folder via this plugin (if different than the default alphabetical order).
- last (but not least) is forcing the hidden file or folder to reappear in File Explorer: in most cases the hidden item reappears automatically when you click the ribbon button to temporarily suspend the custom sorting. At the same time, in older versions of Obsidian I had to disable the plugin and restart Obsidian to show the hidden items. This was the main reason to make this feature experimental and not documented. It looks that newer Obsidians can handle the scenario more gracefully without the need to restart. I didn't perform any extensive testing of this specific scenario

Ok, being warned, here go the instructions if you want to hide a folder or a file
- use `/--hide:` or `--%` (both tokens are equivalent) followed by the name of file or folder
- it must occur in a context of explicit or implicit `target-folder:`
- to hide files use the name of their underlying file, which means `.md` suffix
- no paths are allowed, only direct names. It means, a file or folder can be hidden only by a dedicated entry in `sorting-spec:` for its parent folder
- intentionally, there are no wildcard- or regexp-based specifications of items to hide

Examples:

```yaml
---
sorting-spec: |
  target-folder: /
  /--hide: Development
  /--hide: sortspec.md
---
```

The above example hides a folder `Development` and a file `sortspec.md` in the root folder of the Vault
Implicitly, the sorting order of root folder goes under the control of custom sorting plugin and changing the UI sorting selection has no effect on root folder entries

```yaml
---
sorting-spec: |
  target-folder: Development
  /--hide: C
  /--hide: sortspec.md
---
```

The above example hides a folder `Development/C` and a file `Development/sortspec.md`
Implicitly, the sorting order of the `Development` folder goes under the control of custom sorting plugin and changing the UI sorting selection has no effect on root folder entries

**Comment by replete** [comment]
Quality stuff, Sebastian!

Thanks for yet another comprehensive solution.
