### ISSUE TITLE
[Feature Request] Reload sortspec command

### ISSUE THREAD

**Issue by replete** [SebastianMC/obsidian-custom-sort#62]
Not really a big issue, but while I'm here I'll mention it:

While I was designing my vault and making sort adjustments, I had to press a lot of keys to reload my sortspec. I improved this by making a `Commander` macro with `sort off` and `sort on`.

It would be a mild improvement to have a single command to turn it off and on again in this scenario.

Auto-reload watching sortspec came to mind also, but Obsidian seems to save/update notes quite frequently and I could imagine this might be get the plugin's knickers in a twist...

**Comment by SebastianMC** [comment]
The plugin supports two commands, which can be invoked from the Obsidian commands palette.
While the full names of the commands are long, they can be invoked by typing in **sort on** or **sort off** (or **sort-on** or **sort-off**) thanks to the convenience of Obsidian UI:

![custom sort commands](https://user-images.githubusercontent.com/23032356/221904742-1c68c2d3-fcc4-4244-94d3-f690d77eb70d.jpg)

- **sort on**, as the description states, (re)parses the sorting specification and applies it, regardless of current plugin state
- **sort off**, suspends the custom sorting

I will add description of the commands to plugin documentation
