### ISSUE TITLE
Feature request: alphabetic wildcard

### ISSUE THREAD

**Issue by bszonye** [SebastianMC/obsidian-custom-sort#67]
I like to organize my notes like books, with separate groups for front matter, main text, and back matter:

i. Foreword
ii. Preface
iii. Introduction
1\. First main section
2\. Second section
3\. Third section
A. First appendix
B. Second appendix
Attachments
Diagrams
Etc.

I'm currently using a sortspec with these patterns:
```
\R+. ...
\d+. ...
App. ...
%
```

I would prefer to replace the `App. ...` with `\a+. ...` so that I can shorten those to a single-letter abbreviation like the Roman & Arabic numerals.

**Comment by SebastianMC** [comment]
Hi @bszonye,

the newest release [1.7.1](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/1.7.1) adds support for two new sorting / grouping symbols (#67):
- `\a+` to match any ASCII word
- `\A+` to match any modern language word

**Comment by bszonye** [comment]
Awesome, thanks!
