### ISSUE TITLE
Feature Request: Add option to pin folder notes

### ISSUE THREAD

**Issue by maizehsu** [SebastianMC/obsidian-custom-sort#79]
I have a folder note for each of my projects under each project directory. It would be nice if, instead of specifying target folder for each project, there's an option for pinning folder note, or even better, a variable such as {%foldername%} for sorting spec.

For example,
```
---
target-folder: /*
... GTD
{%foldername%}
---
```
would put foldernotes after all notes that ends with GTD.

**Comment by SebastianMC** [comment]
Hi @maizehsu,

Implementation completed and available in recent release ([1.8.0](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/1.8.0)) of the plugin

The final syntax is `{:%parent-folder-name%:}`, it fits seamlessly with already supported grammar and cannot be confused with a name of a real note (the `:` character is forbidden in folder and file names)

The example sorting spec reflecting your idea looks like:
```
---
sorting-spec: |
  target-folder: /*
  ... GTD
  {:%parent-folder-name%:}
---
```
