### ISSUE TITLE
Add the ability to set a custom sort-title or exclude specific strings/chars

### ISSUE THREAD

**Issue by fischgeek** [SebastianMC/obsidian-custom-sort#80]
Is it possible with this to exclude a string or specific chars or just allow regex patterns to sort the list? 

A quick example would be, 
* sort alphabetical
* ignore the string `the`

Or, even better, have it sort based on meta-data within the note with a `sort-title` key/value pair.

```
The Awesome Note.md
---
sort-title: 'awesome note'
---
```

**Comment by SebastianMC** [comment]
Hi @fischgeek 

sorting by metadata value has been already supported as a result of feature request #23
Simple documentation of that feature is available in #23 and also in [example 14 of advanced-manual](https://github.com/SebastianMC/obsidian-custom-sort/blob/master/advanced-README.md#example-14-grouping-and-sorting-by-metadata-value)

For the metadata from your example:
`sort-title: 'awesome note'`

the simplest sorting specification to order by metadata in the root vault folder looks like:
```
---
sorting-spec: |
    target-folder: /
    < a-z by-metadata: sort-title
---
```
Entries in root folder not having the `sort-title` metadata will land below these with the metadata.
Grouping by metadata is also supported, if you want consciously handle the cases of different metadata fields and/or order items with and without metadata in the same folder.

For other questions in your message:
- excluding words or phrases of note's title from sorting is not supported
- regexps are supported in a limited way. Fully free-form regexps not allowed intentionally for folder entries matching
  - at the same time regexps are supported in the `target-folder:` syntax, yet this is not what you are asking for 

Let me know if you have more questions

**Comment by fischgeek** [comment]
Thanks so much for the detailed reply @SebastianMC! I'm going to try the meta-data sort right now!

**Comment by fischgeek** [comment]
The plugin won't install for me. Just fails with no reason.

**Comment by SebastianMC** [comment]
Please try now, the 1.8.2 version is correctly published on github.
I messed up the version numbers in the relevant json files vs the release package content and tags.

**Comment by fischgeek** [comment]
Perfect! Thank you!
