### ISSUE TITLE
Supply additional sort rules when initial criteria don't fully specify order

### ISSUE THREAD

**Issue by edemko** [SebastianMC/obsidian-custom-sort#85]
I have tried everything I can find/think of to get this to work, but in lieu of that awful title, lemme give my concrete example:

I've got a folder of journal entries labelled with human-redabnle rough date-times (oh, and some of the times are missing smh):

- 28 August 12021 - 1
- 28 August 12021 - 2
- Afternoon 24 August 12021
- Evening 24 August 12021
- Evening 28th August 12021

I'd like to sort these descending by date, but ascending by time/sequence number.
I've added `date` and `time` metadata fields (perhaps someday I'll be able to do this from the filename but for now I'm going for easy mode first).
Sorting by only one or the other does give the expected results, but when I try to combine them, everything goes wonky.

```
    target-folder: Journal
    > a-z by-metadata: date, < a-z by-metadata: time
```
gives
- Evening 28th August 12021 `date: 2021-08-28` `time: 5`
- Evening 24 August 12021 `date: 2021-08-24` `time: 5`
- Afternoon 24 August 12021 `date: 2021-08-24` `time: 4`
- 28 August 12021 - 2 `date: 2021-08-28` `time: 0.2`
- 28 August 12021 - 1 `date: 2021-08-28` `time: 0.1`

which looks like descending time, then descending date within those groups.
Oddly, `> a-z by-metadata: time, < a-z by-metadata: date` does not change the order.
To be fair, I can't really tell what comma is _supposed_ to be doing anyway.

```
    target-folder: Journal
    > a-z by-metadata: date
     < a-z by-metadata: time
```
gives
- Evening 28th August 12021 `date: 2021-08-28` `time: 5`
- 28 August 12021 - 2 `date: 2021-08-28` `time: 0.2`
- 28 August 12021 - 1 `date: 2021-08-28` `time: 0.1`
- Evening 24 August 12021 `date: 2021-08-24` `time: 5`
- Afternoon 24 August 12021 `date: 2021-08-24` `time: 4`
which appears to be doing what I want, except that it's sorting time in the reverse of how I want it.
Interestingly, if I swap the time to descending, the order is unchanged, and likewise if I _delete_ the line mentioning time!
The syntax reference seems to tell my I'm barking up the wrong tree with this syntax, but I'm not sure.

I did try `/!` operators at one point, but it didn't work, and the docs suggest that's not right either.

At this point, anything is helpful! I'm not even convinced this capability exists (yet!).

**Comment by SebastianMC** [comment]
The multi-level sorting feature is available in [1.9.0](https://github.com/SebastianMC/obsidian-custom-sort/releases/tag/1.9.0) release of the plugin.
More detailed documentation will follow.

For the specific example described in this thread, the final syntax is:
```yaml
---
  target-folder: Journal
  > a-z by-metadata: date, < a-z by-metadata: time
---
```

In other words:
- same line,
- secondary level sorting order is separated by comma
- two levels supported for now
- theoretically up to four levels can be specified, yet in most cases the two levels should be sufficient
